"""Add is_active column

Revision ID: 17fdf70c40d1
Revises: 
Create Date: 2025-04-30 22:23:10.501429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fdf70c40d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('esner', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esner', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


